spring:
  data:
    rest:
      max-page-size: 30
      default-page-size: 20
      basePath: /api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/dvdrental"
    username: narif
    password: password